package com.bullshit.endpoint.dao;

import java.util.List;

import com.bullshit.endpoint.entity.Cases;

public interface CasesExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_case
     *
     * @mbggenerated
     */
    List<Cases> selectByPatId(String patId);
}