package com.bullshit.endpoint.dao;

import com.bullshit.endpoint.entity.Cases;

public interface CasesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_case
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String caseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_case
     *
     * @mbggenerated
     */
    int insert(Cases record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_case
     *
     * @mbggenerated
     */
    int insertSelective(Cases record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_case
     *
     * @mbggenerated
     */
    Cases selectByPrimaryKey(String caseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_case
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Cases record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pat_case
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Cases record);
}