package com.bullshit.endpoint.dao;

import java.util.List;

import com.bullshit.endpoint.entity.Department;

public interface DepartmentExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated
     */
    List<Department> selectByName();
}