package com.bullshit.endpoint.dao;

import java.util.List;

import com.bullshit.endpoint.entity.DocPatRelation;

public interface DocPatRelationExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_pat_relation
     *
     * @mbggenerated
     */
    List<DocPatRelation> selectRelationPatInfoByDocId(String docId);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_pat_relation
     *
     * @mbggenerated
     */
    List<DocPatRelation> selectRelationPatInfoByPatId(String patId);
}