package com.bullshit.endpoint.dao;

import com.bullshit.endpoint.entity.DocPatRelation;
import com.bullshit.endpoint.entity.DocPatRelationKey;

public interface DocPatRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_pat_relation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(DocPatRelationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_pat_relation
     *
     * @mbggenerated
     */
    int insert(DocPatRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_pat_relation
     *
     * @mbggenerated
     */
    int insertSelective(DocPatRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_pat_relation
     *
     * @mbggenerated
     */
    DocPatRelation selectByPrimaryKey(DocPatRelationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_pat_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DocPatRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_pat_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DocPatRelation record);
}