package com.bullshit.endpoint.dao;

import com.bullshit.endpoint.entity.DocSurgeryPlan;

public interface DocSurgeryPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_surgery_plan
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String planId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_surgery_plan
     *
     * @mbggenerated
     */
    int insert(DocSurgeryPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_surgery_plan
     *
     * @mbggenerated
     */
    int insertSelective(DocSurgeryPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_surgery_plan
     *
     * @mbggenerated
     */
    DocSurgeryPlan selectByPrimaryKey(String planId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_surgery_plan
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DocSurgeryPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_surgery_plan
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DocSurgeryPlan record);
}