package com.bullshit.endpoint.dao;

import java.util.List;

import com.bullshit.endpoint.entity.DocSurgeryPlan;
import com.bullshit.endpoint.entity.DocSurgeryPlanKey;

public interface DocSurgeryPlanExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_surgery_plan
     *
     * @mbggenerated
     */
    List<DocSurgeryPlan> selectByDocId(DocSurgeryPlanKey key);
}