package com.bullshit.endpoint.dao;

import java.util.List;

import com.bullshit.endpoint.entity.Hospital;
import com.bullshit.endpoint.entity.HospitalKey;

public interface HospitalExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbggenerated
     */
    List<Hospital> selectInfoList(HospitalKey hospitalKey);
}