package com.bullshit.endpoint.dao;

import com.bullshit.endpoint.entity.VersionControl;

public interface VersionControlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_control
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_control
     *
     * @mbggenerated
     */
    int insert(VersionControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_control
     *
     * @mbggenerated
     */
    int insertSelective(VersionControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_control
     *
     * @mbggenerated
     */
    VersionControl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_control
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VersionControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table version_control
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VersionControl record);
}