package com.bullshit.endpoint.entity;

import java.util.Date;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.pw
     *
     * @mbggenerated
     */
    private String pw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.roleflg
     *
     * @mbggenerated
     */
    private String roleflg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.isactive
     *
     * @mbggenerated
     */
    private String isactive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.imageurl
     *
     * @mbggenerated
     */
    private String imageurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.age
     *
     * @mbggenerated
     */
    private String age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.mobile_phone
     *
     * @mbggenerated
     */
    private String mobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.tel_phone
     *
     * @mbggenerated
     */
    private String telPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.ctime
     *
     * @mbggenerated
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.mtime
     *
     * @mbggenerated
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.doc_title
     *
     * @mbggenerated
     */
    private String docTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.doc_professional
     *
     * @mbggenerated
     */
    private String docProfessional;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.doc_description
     *
     * @mbggenerated
     */
    private String docDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.doc_hospital
     *
     * @mbggenerated
     */
    private String docHospital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.doc_department_name
     *
     * @mbggenerated
     */
    private String docDepartmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.pat_past_history
     *
     * @mbggenerated
     */
    private String patPastHistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.pat_allergy_drug
     *
     * @mbggenerated
     */
    private String patAllergyDrug;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.pat_emerg_person
     *
     * @mbggenerated
     */
    private String patEmergPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.pat_emerg_phone
     *
     * @mbggenerated
     */
    private String patEmergPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.pat_status_flg
     *
     * @mbggenerated
     */
    private String patStatusFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.hxusername
     *
     * @mbggenerated
     */
    private String hxusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.hxpassword
     *
     * @mbggenerated
     */
    private String hxpassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.id
     *
     * @return the value of account.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.id
     *
     * @param id the value for account.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.pw
     *
     * @return the value of account.pw
     *
     * @mbggenerated
     */
    public String getPw() {
        return pw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.pw
     *
     * @param pw the value for account.pw
     *
     * @mbggenerated
     */
    public void setPw(String pw) {
        this.pw = pw == null ? null : pw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.roleflg
     *
     * @return the value of account.roleflg
     *
     * @mbggenerated
     */
    public String getRoleflg() {
        return roleflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.roleflg
     *
     * @param roleflg the value for account.roleflg
     *
     * @mbggenerated
     */
    public void setRoleflg(String roleflg) {
        this.roleflg = roleflg == null ? null : roleflg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.isactive
     *
     * @return the value of account.isactive
     *
     * @mbggenerated
     */
    public String getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.isactive
     *
     * @param isactive the value for account.isactive
     *
     * @mbggenerated
     */
    public void setIsactive(String isactive) {
        this.isactive = isactive == null ? null : isactive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.name
     *
     * @return the value of account.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.name
     *
     * @param name the value for account.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.imageurl
     *
     * @return the value of account.imageurl
     *
     * @mbggenerated
     */
    public String getImageurl() {
        return imageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.imageurl
     *
     * @param imageurl the value for account.imageurl
     *
     * @mbggenerated
     */
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl == null ? null : imageurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.age
     *
     * @return the value of account.age
     *
     * @mbggenerated
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.age
     *
     * @param age the value for account.age
     *
     * @mbggenerated
     */
    public void setAge(String age) {
        this.age = age == null ? null : age.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.sex
     *
     * @return the value of account.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.sex
     *
     * @param sex the value for account.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.mobile_phone
     *
     * @return the value of account.mobile_phone
     *
     * @mbggenerated
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.mobile_phone
     *
     * @param mobilePhone the value for account.mobile_phone
     *
     * @mbggenerated
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.tel_phone
     *
     * @return the value of account.tel_phone
     *
     * @mbggenerated
     */
    public String getTelPhone() {
        return telPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.tel_phone
     *
     * @param telPhone the value for account.tel_phone
     *
     * @mbggenerated
     */
    public void setTelPhone(String telPhone) {
        this.telPhone = telPhone == null ? null : telPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.ctime
     *
     * @return the value of account.ctime
     *
     * @mbggenerated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.ctime
     *
     * @param ctime the value for account.ctime
     *
     * @mbggenerated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.mtime
     *
     * @return the value of account.mtime
     *
     * @mbggenerated
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.mtime
     *
     * @param mtime the value for account.mtime
     *
     * @mbggenerated
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.doc_title
     *
     * @return the value of account.doc_title
     *
     * @mbggenerated
     */
    public String getDocTitle() {
        return docTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.doc_title
     *
     * @param docTitle the value for account.doc_title
     *
     * @mbggenerated
     */
    public void setDocTitle(String docTitle) {
        this.docTitle = docTitle == null ? null : docTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.doc_professional
     *
     * @return the value of account.doc_professional
     *
     * @mbggenerated
     */
    public String getDocProfessional() {
        return docProfessional;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.doc_professional
     *
     * @param docProfessional the value for account.doc_professional
     *
     * @mbggenerated
     */
    public void setDocProfessional(String docProfessional) {
        this.docProfessional = docProfessional == null ? null : docProfessional.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.doc_description
     *
     * @return the value of account.doc_description
     *
     * @mbggenerated
     */
    public String getDocDescription() {
        return docDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.doc_description
     *
     * @param docDescription the value for account.doc_description
     *
     * @mbggenerated
     */
    public void setDocDescription(String docDescription) {
        this.docDescription = docDescription == null ? null : docDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.doc_hospital
     *
     * @return the value of account.doc_hospital
     *
     * @mbggenerated
     */
    public String getDocHospital() {
        return docHospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.doc_hospital
     *
     * @param docHospital the value for account.doc_hospital
     *
     * @mbggenerated
     */
    public void setDocHospital(String docHospital) {
        this.docHospital = docHospital == null ? null : docHospital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.doc_department_name
     *
     * @return the value of account.doc_department_name
     *
     * @mbggenerated
     */
    public String getDocDepartmentName() {
        return docDepartmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.doc_department_name
     *
     * @param docDepartmentName the value for account.doc_department_name
     *
     * @mbggenerated
     */
    public void setDocDepartmentName(String docDepartmentName) {
        this.docDepartmentName = docDepartmentName == null ? null : docDepartmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.pat_past_history
     *
     * @return the value of account.pat_past_history
     *
     * @mbggenerated
     */
    public String getPatPastHistory() {
        return patPastHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.pat_past_history
     *
     * @param patPastHistory the value for account.pat_past_history
     *
     * @mbggenerated
     */
    public void setPatPastHistory(String patPastHistory) {
        this.patPastHistory = patPastHistory == null ? null : patPastHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.pat_allergy_drug
     *
     * @return the value of account.pat_allergy_drug
     *
     * @mbggenerated
     */
    public String getPatAllergyDrug() {
        return patAllergyDrug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.pat_allergy_drug
     *
     * @param patAllergyDrug the value for account.pat_allergy_drug
     *
     * @mbggenerated
     */
    public void setPatAllergyDrug(String patAllergyDrug) {
        this.patAllergyDrug = patAllergyDrug == null ? null : patAllergyDrug.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.pat_emerg_person
     *
     * @return the value of account.pat_emerg_person
     *
     * @mbggenerated
     */
    public String getPatEmergPerson() {
        return patEmergPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.pat_emerg_person
     *
     * @param patEmergPerson the value for account.pat_emerg_person
     *
     * @mbggenerated
     */
    public void setPatEmergPerson(String patEmergPerson) {
        this.patEmergPerson = patEmergPerson == null ? null : patEmergPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.pat_emerg_phone
     *
     * @return the value of account.pat_emerg_phone
     *
     * @mbggenerated
     */
    public String getPatEmergPhone() {
        return patEmergPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.pat_emerg_phone
     *
     * @param patEmergPhone the value for account.pat_emerg_phone
     *
     * @mbggenerated
     */
    public void setPatEmergPhone(String patEmergPhone) {
        this.patEmergPhone = patEmergPhone == null ? null : patEmergPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.pat_status_flg
     *
     * @return the value of account.pat_status_flg
     *
     * @mbggenerated
     */
    public String getPatStatusFlg() {
        return patStatusFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.pat_status_flg
     *
     * @param patStatusFlg the value for account.pat_status_flg
     *
     * @mbggenerated
     */
    public void setPatStatusFlg(String patStatusFlg) {
        this.patStatusFlg = patStatusFlg == null ? null : patStatusFlg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.hxusername
     *
     * @return the value of account.hxusername
     *
     * @mbggenerated
     */
    public String getHxusername() {
        return hxusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.hxusername
     *
     * @param hxusername the value for account.hxusername
     *
     * @mbggenerated
     */
    public void setHxusername(String hxusername) {
        this.hxusername = hxusername == null ? null : hxusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.hxpassword
     *
     * @return the value of account.hxpassword
     *
     * @mbggenerated
     */
    public String getHxpassword() {
        return hxpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.hxpassword
     *
     * @param hxpassword the value for account.hxpassword
     *
     * @mbggenerated
     */
    public void setHxpassword(String hxpassword) {
        this.hxpassword = hxpassword == null ? null : hxpassword.trim();
    }
}