package com.bullshit.endpoint.entity;

import java.util.Date;

public class Cases {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pat_case.case_id
     *
     * @mbggenerated
     */
    private String caseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pat_case.pat_id
     *
     * @mbggenerated
     */
    private String patId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pat_case.isactive
     *
     * @mbggenerated
     */
    private String isactive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pat_case.pat_report
     *
     * @mbggenerated
     */
    private String patReport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pat_case.pat_pic_url_1
     *
     * @mbggenerated
     */
    private String patPicUrl1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pat_case.pat_pic_url_2
     *
     * @mbggenerated
     */
    private String patPicUrl2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pat_case.pat_pic_url_3
     *
     * @mbggenerated
     */
    private String patPicUrl3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pat_case.doc_suggestion
     *
     * @mbggenerated
     */
    private String docSuggestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pat_case.ctime
     *
     * @mbggenerated
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pat_case.mtime
     *
     * @mbggenerated
     */
    private Date mtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pat_case.case_id
     *
     * @return the value of pat_case.case_id
     *
     * @mbggenerated
     */
    public String getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pat_case.case_id
     *
     * @param caseId the value for pat_case.case_id
     *
     * @mbggenerated
     */
    public void setCaseId(String caseId) {
        this.caseId = caseId == null ? null : caseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pat_case.pat_id
     *
     * @return the value of pat_case.pat_id
     *
     * @mbggenerated
     */
    public String getPatId() {
        return patId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pat_case.pat_id
     *
     * @param patId the value for pat_case.pat_id
     *
     * @mbggenerated
     */
    public void setPatId(String patId) {
        this.patId = patId == null ? null : patId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pat_case.isactive
     *
     * @return the value of pat_case.isactive
     *
     * @mbggenerated
     */
    public String getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pat_case.isactive
     *
     * @param isactive the value for pat_case.isactive
     *
     * @mbggenerated
     */
    public void setIsactive(String isactive) {
        this.isactive = isactive == null ? null : isactive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pat_case.pat_report
     *
     * @return the value of pat_case.pat_report
     *
     * @mbggenerated
     */
    public String getPatReport() {
        return patReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pat_case.pat_report
     *
     * @param patReport the value for pat_case.pat_report
     *
     * @mbggenerated
     */
    public void setPatReport(String patReport) {
        this.patReport = patReport == null ? null : patReport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pat_case.pat_pic_url_1
     *
     * @return the value of pat_case.pat_pic_url_1
     *
     * @mbggenerated
     */
    public String getPatPicUrl1() {
        return patPicUrl1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pat_case.pat_pic_url_1
     *
     * @param patPicUrl1 the value for pat_case.pat_pic_url_1
     *
     * @mbggenerated
     */
    public void setPatPicUrl1(String patPicUrl1) {
        this.patPicUrl1 = patPicUrl1 == null ? null : patPicUrl1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pat_case.pat_pic_url_2
     *
     * @return the value of pat_case.pat_pic_url_2
     *
     * @mbggenerated
     */
    public String getPatPicUrl2() {
        return patPicUrl2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pat_case.pat_pic_url_2
     *
     * @param patPicUrl2 the value for pat_case.pat_pic_url_2
     *
     * @mbggenerated
     */
    public void setPatPicUrl2(String patPicUrl2) {
        this.patPicUrl2 = patPicUrl2 == null ? null : patPicUrl2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pat_case.pat_pic_url_3
     *
     * @return the value of pat_case.pat_pic_url_3
     *
     * @mbggenerated
     */
    public String getPatPicUrl3() {
        return patPicUrl3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pat_case.pat_pic_url_3
     *
     * @param patPicUrl3 the value for pat_case.pat_pic_url_3
     *
     * @mbggenerated
     */
    public void setPatPicUrl3(String patPicUrl3) {
        this.patPicUrl3 = patPicUrl3 == null ? null : patPicUrl3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pat_case.doc_suggestion
     *
     * @return the value of pat_case.doc_suggestion
     *
     * @mbggenerated
     */
    public String getDocSuggestion() {
        return docSuggestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pat_case.doc_suggestion
     *
     * @param docSuggestion the value for pat_case.doc_suggestion
     *
     * @mbggenerated
     */
    public void setDocSuggestion(String docSuggestion) {
        this.docSuggestion = docSuggestion == null ? null : docSuggestion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pat_case.ctime
     *
     * @return the value of pat_case.ctime
     *
     * @mbggenerated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pat_case.ctime
     *
     * @param ctime the value for pat_case.ctime
     *
     * @mbggenerated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pat_case.mtime
     *
     * @return the value of pat_case.mtime
     *
     * @mbggenerated
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pat_case.mtime
     *
     * @param mtime the value for pat_case.mtime
     *
     * @mbggenerated
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }
}