package com.bullshit.endpoint.entity;

import java.util.Date;

public class DocPatRelation extends DocPatRelationKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_pat_relation.isactive
     *
     * @mbggenerated
     */
    private String isactive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_pat_relation.ctime
     *
     * @mbggenerated
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_pat_relation.mtime
     *
     * @mbggenerated
     */
    private Date mtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc_pat_relation.isactive
     *
     * @return the value of doc_pat_relation.isactive
     *
     * @mbggenerated
     */
    public String getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc_pat_relation.isactive
     *
     * @param isactive the value for doc_pat_relation.isactive
     *
     * @mbggenerated
     */
    public void setIsactive(String isactive) {
        this.isactive = isactive == null ? null : isactive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc_pat_relation.ctime
     *
     * @return the value of doc_pat_relation.ctime
     *
     * @mbggenerated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc_pat_relation.ctime
     *
     * @param ctime the value for doc_pat_relation.ctime
     *
     * @mbggenerated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc_pat_relation.mtime
     *
     * @return the value of doc_pat_relation.mtime
     *
     * @mbggenerated
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc_pat_relation.mtime
     *
     * @param mtime the value for doc_pat_relation.mtime
     *
     * @mbggenerated
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }
}