package com.bullshit.endpoint.entity;

public class DocPatRelationKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_pat_relation.doc_id
     *
     * @mbggenerated
     */
    private String docId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_pat_relation.pat_id
     *
     * @mbggenerated
     */
    private String patId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc_pat_relation.doc_id
     *
     * @return the value of doc_pat_relation.doc_id
     *
     * @mbggenerated
     */
    public String getDocId() {
        return docId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc_pat_relation.doc_id
     *
     * @param docId the value for doc_pat_relation.doc_id
     *
     * @mbggenerated
     */
    public void setDocId(String docId) {
        this.docId = docId == null ? null : docId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc_pat_relation.pat_id
     *
     * @return the value of doc_pat_relation.pat_id
     *
     * @mbggenerated
     */
    public String getPatId() {
        return patId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc_pat_relation.pat_id
     *
     * @param patId the value for doc_pat_relation.pat_id
     *
     * @mbggenerated
     */
    public void setPatId(String patId) {
        this.patId = patId == null ? null : patId.trim();
    }
}