package com.bullshit.endpoint.entity;

import java.util.Date;

public class DocSurgeryPlan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_surgery_plan.plan_Id
     *
     * @mbggenerated
     */
    private String planId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_surgery_plan.doc_id
     *
     * @mbggenerated
     */
    private String docId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_surgery_plan.isactive
     *
     * @mbggenerated
     */
    private String isactive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_surgery_plan.surgery_plan_pic_url
     *
     * @mbggenerated
     */
    private String surgeryPlanPicUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_surgery_plan.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_surgery_plan.ctime
     *
     * @mbggenerated
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_surgery_plan.mtime
     *
     * @mbggenerated
     */
    private Date mtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc_surgery_plan.plan_Id
     *
     * @return the value of doc_surgery_plan.plan_Id
     *
     * @mbggenerated
     */
    public String getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc_surgery_plan.plan_Id
     *
     * @param planId the value for doc_surgery_plan.plan_Id
     *
     * @mbggenerated
     */
    public void setPlanId(String planId) {
        this.planId = planId == null ? null : planId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc_surgery_plan.doc_id
     *
     * @return the value of doc_surgery_plan.doc_id
     *
     * @mbggenerated
     */
    public String getDocId() {
        return docId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc_surgery_plan.doc_id
     *
     * @param docId the value for doc_surgery_plan.doc_id
     *
     * @mbggenerated
     */
    public void setDocId(String docId) {
        this.docId = docId == null ? null : docId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc_surgery_plan.isactive
     *
     * @return the value of doc_surgery_plan.isactive
     *
     * @mbggenerated
     */
    public String getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc_surgery_plan.isactive
     *
     * @param isactive the value for doc_surgery_plan.isactive
     *
     * @mbggenerated
     */
    public void setIsactive(String isactive) {
        this.isactive = isactive == null ? null : isactive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc_surgery_plan.surgery_plan_pic_url
     *
     * @return the value of doc_surgery_plan.surgery_plan_pic_url
     *
     * @mbggenerated
     */
    public String getSurgeryPlanPicUrl() {
        return surgeryPlanPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc_surgery_plan.surgery_plan_pic_url
     *
     * @param surgeryPlanPicUrl the value for doc_surgery_plan.surgery_plan_pic_url
     *
     * @mbggenerated
     */
    public void setSurgeryPlanPicUrl(String surgeryPlanPicUrl) {
        this.surgeryPlanPicUrl = surgeryPlanPicUrl == null ? null : surgeryPlanPicUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc_surgery_plan.description
     *
     * @return the value of doc_surgery_plan.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc_surgery_plan.description
     *
     * @param description the value for doc_surgery_plan.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc_surgery_plan.ctime
     *
     * @return the value of doc_surgery_plan.ctime
     *
     * @mbggenerated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc_surgery_plan.ctime
     *
     * @param ctime the value for doc_surgery_plan.ctime
     *
     * @mbggenerated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc_surgery_plan.mtime
     *
     * @return the value of doc_surgery_plan.mtime
     *
     * @mbggenerated
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc_surgery_plan.mtime
     *
     * @param mtime the value for doc_surgery_plan.mtime
     *
     * @mbggenerated
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }
}