package com.bullshit.endpoint.entity;

public class Hospital {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.hospital_id
     *
     * @mbggenerated
     */
    private String hospitalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.hospital_tel
     *
     * @mbggenerated
     */
    private String hospitalTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.hospital_province
     *
     * @mbggenerated
     */
    private String hospitalProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.hospital_name
     *
     * @mbggenerated
     */
    private String hospitalName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.hospital_type
     *
     * @mbggenerated
     */
    private String hospitalType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.hospital_address
     *
     * @mbggenerated
     */
    private String hospitalAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.hospital_id
     *
     * @return the value of hospital.hospital_id
     *
     * @mbggenerated
     */
    public String getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.hospital_id
     *
     * @param hospitalId the value for hospital.hospital_id
     *
     * @mbggenerated
     */
    public void setHospitalId(String hospitalId) {
        this.hospitalId = hospitalId == null ? null : hospitalId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.hospital_tel
     *
     * @return the value of hospital.hospital_tel
     *
     * @mbggenerated
     */
    public String getHospitalTel() {
        return hospitalTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.hospital_tel
     *
     * @param hospitalTel the value for hospital.hospital_tel
     *
     * @mbggenerated
     */
    public void setHospitalTel(String hospitalTel) {
        this.hospitalTel = hospitalTel == null ? null : hospitalTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.hospital_province
     *
     * @return the value of hospital.hospital_province
     *
     * @mbggenerated
     */
    public String getHospitalProvince() {
        return hospitalProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.hospital_province
     *
     * @param hospitalProvince the value for hospital.hospital_province
     *
     * @mbggenerated
     */
    public void setHospitalProvince(String hospitalProvince) {
        this.hospitalProvince = hospitalProvince == null ? null : hospitalProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.hospital_name
     *
     * @return the value of hospital.hospital_name
     *
     * @mbggenerated
     */
    public String getHospitalName() {
        return hospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.hospital_name
     *
     * @param hospitalName the value for hospital.hospital_name
     *
     * @mbggenerated
     */
    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName == null ? null : hospitalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.hospital_type
     *
     * @return the value of hospital.hospital_type
     *
     * @mbggenerated
     */
    public String getHospitalType() {
        return hospitalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.hospital_type
     *
     * @param hospitalType the value for hospital.hospital_type
     *
     * @mbggenerated
     */
    public void setHospitalType(String hospitalType) {
        this.hospitalType = hospitalType == null ? null : hospitalType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.hospital_address
     *
     * @return the value of hospital.hospital_address
     *
     * @mbggenerated
     */
    public String getHospitalAddress() {
        return hospitalAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.hospital_address
     *
     * @param hospitalAddress the value for hospital.hospital_address
     *
     * @mbggenerated
     */
    public void setHospitalAddress(String hospitalAddress) {
        this.hospitalAddress = hospitalAddress == null ? null : hospitalAddress.trim();
    }
}