package com.bullshit.endpoint.entity;

import java.util.Date;

public class VersionControl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_control.Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_control.version_number
     *
     * @mbggenerated
     */
    private String versionNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_control.version_url
     *
     * @mbggenerated
     */
    private String versionUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_control.version_description
     *
     * @mbggenerated
     */
    private String versionDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_control.version_update_datetime
     *
     * @mbggenerated
     */
    private String versionUpdateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_control.isactive
     *
     * @mbggenerated
     */
    private String isactive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_control.ctime
     *
     * @mbggenerated
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version_control.mtime
     *
     * @mbggenerated
     */
    private Date mtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_control.Id
     *
     * @return the value of version_control.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_control.Id
     *
     * @param id the value for version_control.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_control.version_number
     *
     * @return the value of version_control.version_number
     *
     * @mbggenerated
     */
    public String getVersionNumber() {
        return versionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_control.version_number
     *
     * @param versionNumber the value for version_control.version_number
     *
     * @mbggenerated
     */
    public void setVersionNumber(String versionNumber) {
        this.versionNumber = versionNumber == null ? null : versionNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_control.version_url
     *
     * @return the value of version_control.version_url
     *
     * @mbggenerated
     */
    public String getVersionUrl() {
        return versionUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_control.version_url
     *
     * @param versionUrl the value for version_control.version_url
     *
     * @mbggenerated
     */
    public void setVersionUrl(String versionUrl) {
        this.versionUrl = versionUrl == null ? null : versionUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_control.version_description
     *
     * @return the value of version_control.version_description
     *
     * @mbggenerated
     */
    public String getVersionDescription() {
        return versionDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_control.version_description
     *
     * @param versionDescription the value for version_control.version_description
     *
     * @mbggenerated
     */
    public void setVersionDescription(String versionDescription) {
        this.versionDescription = versionDescription == null ? null : versionDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_control.version_update_datetime
     *
     * @return the value of version_control.version_update_datetime
     *
     * @mbggenerated
     */
    public String getVersionUpdateDatetime() {
        return versionUpdateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_control.version_update_datetime
     *
     * @param versionUpdateDatetime the value for version_control.version_update_datetime
     *
     * @mbggenerated
     */
    public void setVersionUpdateDatetime(String versionUpdateDatetime) {
        this.versionUpdateDatetime = versionUpdateDatetime == null ? null : versionUpdateDatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_control.isactive
     *
     * @return the value of version_control.isactive
     *
     * @mbggenerated
     */
    public String getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_control.isactive
     *
     * @param isactive the value for version_control.isactive
     *
     * @mbggenerated
     */
    public void setIsactive(String isactive) {
        this.isactive = isactive == null ? null : isactive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_control.ctime
     *
     * @return the value of version_control.ctime
     *
     * @mbggenerated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_control.ctime
     *
     * @param ctime the value for version_control.ctime
     *
     * @mbggenerated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version_control.mtime
     *
     * @return the value of version_control.mtime
     *
     * @mbggenerated
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version_control.mtime
     *
     * @param mtime the value for version_control.mtime
     *
     * @mbggenerated
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }
}